"use client";
import Image from "next/image";
import Link from "next/link";
import { useState } from "react";
import { Instagram, Menu, X } from "./icons";
import { ThemeToggle } from "./theme-toggle";

const primary=[["Notícias","/noticias","news"],["Eventos","/eventos","events"],["Olhares CAECOMP","/olhares","photo_initiatives"],["Produtos","/produtos","ca_products"],["Vendinhas","/vendinhas","stores"]] as const;
const more=[["Oportunidades","/oportunidades","opportunities"],["Documentos e jornal","/documentos","documents"],["Galeria","/galeria","gallery"],["Diretoria e sobre","/sobre","about"]] as const;
export function SiteHeader({sections}:{sections:Record<string,boolean>}){const [open,setOpen]=useState(false);const visible=(items:typeof primary|typeof more)=>items.filter(([, ,key])=>key==="opportunities"?sections.company_opportunities!==false||sections.academic_opportunities!==false:sections[key]!==false);const all=[...visible(primary),...visible(more)];return <header className="site-header"><div className="nav-shell"><Link href="/" className="brand" aria-label="CAECOMP — início"><Image src="/caecomp-logo-official.jpg" width={52} height={52} alt="Símbolo oficial do CAECOMP" priority/><span><strong>CAECOMP</strong><small>Engenharia de Computação · UFG</small></span></Link><nav className="desktop-nav" aria-label="Navegação principal">{visible(primary).map(([label,href])=><Link key={href} href={href}>{label}</Link>)}<details className="nav-more"><summary>Mais</summary><div>{visible(more).map(([label,href])=><Link key={href} href={href}>{label}</Link>)}</div></details></nav><div className="nav-actions"><ThemeToggle/><a href="https://www.instagram.com/caecompufg/" target="_blank" rel="noopener noreferrer" aria-label="Instagram oficial do CAECOMP"><Instagram size={19}/></a><Link href="/admin" className="admin-link">Painel</Link><button className="menu-button" onClick={()=>setOpen(!open)} aria-expanded={open} aria-controls="mobile-navigation" aria-label={open?"Fechar menu":"Abrir menu"}>{open?<X/>:<Menu/>}</button></div></div>{open&&<nav id="mobile-navigation" className="mobile-nav" aria-label="Navegação móvel">{all.map(([label,href])=><Link key={href} href={href} onClick={()=>setOpen(false)}>{label}</Link>)}</nav>}</header>}
