"use client";
import Image from "next/image";
import Link from "next/link";
import { useEffect, useRef, useState } from "react";
import { Instagram, Menu, X } from "./icons";
import { ThemeToggle } from "./theme-toggle";

const primary=[["Notícias","/noticias","news"],["Eventos","/eventos","events"],["Olhares CAECOMP","/olhares","photo_initiatives"],["Produtos","/produtos","ca_products"],["Vendinhas","/vendinhas","stores"]] as const;
const more=[["Oportunidades","/oportunidades","opportunities"],["Calendário","/calendario","calendar"],["Diretorias","/diretorias","departments"],["Documentos e jornal","/documentos","documents"],["Galeria","/galeria","gallery"],["Diretoria e sobre","/sobre","about"]] as const;
export function SiteHeader({sections}:{sections:Record<string,boolean>}){const [open,setOpen]=useState(false);const [moreOpen,setMoreOpen]=useState(false);const moreRef=useRef<HTMLDivElement>(null);useEffect(()=>{const close=(event:MouseEvent)=>{if(moreRef.current&&!moreRef.current.contains(event.target as Node))setMoreOpen(false)};document.addEventListener("mousedown",close);return()=>document.removeEventListener("mousedown",close)},[]);const visible=(items:typeof primary|typeof more)=>items.filter(([, ,key])=>key==="opportunities"?sections.company_opportunities!==false||sections.academic_opportunities!==false:sections[key]!==false);const all=[...visible(primary),...visible(more)];return <header className="site-header"><div className="nav-shell"><Link href="/" className="brand" aria-label="CAECOMP — início"><Image src="/caecomp-logo-official.jpg" width={52} height={52} alt="Símbolo oficial do CAECOMP" priority/><span><strong>CAECOMP</strong><small>Engenharia de Computação · UFG</small></span></Link><nav className="desktop-nav" aria-label="Navegação principal">{visible(primary).map(([label,href])=><Link key={href} href={href}>{label}</Link>)}<div className="nav-more" ref={moreRef}><button type="button" aria-expanded={moreOpen} onClick={()=>setMoreOpen(!moreOpen)}>Mais</button>{moreOpen&&<div>{visible(more).map(([label,href])=><Link key={href} href={href} onClick={()=>setMoreOpen(false)}>{label}</Link>)}</div>}</div></nav><div className="nav-actions"><ThemeToggle/><a href="https://www.instagram.com/caecompufg/" target="_blank" rel="noopener noreferrer" aria-label="Instagram oficial do CAECOMP"><Instagram size={19}/></a><Link href="/admin" className="admin-link">Painel</Link><button className="menu-button" onClick={()=>setOpen(!open)} aria-expanded={open} aria-controls="mobile-navigation" aria-label={open?"Fechar menu":"Abrir menu"}>{open?<X/>:<Menu/>}</button></div></div>{open&&<nav id="mobile-navigation" className="mobile-nav" aria-label="Navegação móvel">{all.map(([label,href])=><Link key={href} href={href} onClick={()=>setOpen(false)}>{label}</Link>)}</nav>}</header>}
