import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import { notFound } from "next/navigation";
import { getApprovedCampaignPhotos } from "../../lib/pretinha";
import { getPublicData, requirePublicSection } from "../../lib/public-data";
import { PretinhaSubmissionForm } from "../../pretinha/submission-form";
export async function generateMetadata({params}:{params:Promise<{slug:string}>}):Promise<Metadata>{const {slug}=await params;const data=await getPublicData();const campaign=data.photoCampaigns.find(c=>c.slug===slug);return {title:campaign?.title??"Olhares CAECOMP",description:campaign?.summary};}
export default async function Page({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const data=await getPublicData();requirePublicSection(data,"photo_initiatives");const campaign=data.photoCampaigns.find(c=>c.slug===slug);if(!campaign)notFound();const photos=await getApprovedCampaignPhotos(campaign.id,campaign.selectionLimit);const open=campaign.status==="open"&&(!campaign.endsAt||new Date(campaign.endsAt)>new Date());return <><section className="pretinha-hero"><div className="pretinha-hero-copy"><span className="kicker light">Olhares CAECOMP</span><h1>{campaign.title}</h1><p>{campaign.description||campaign.summary}</p>{open&&<a href="#enviar" className="button primary">Enviar uma foto</a>}</div><div className="pretinha-number" aria-label={`${campaign.selectionLimit} fotos selecionadas`}><strong>{campaign.selectionLimit}</strong><span>fotos<br/>selecionadas</span></div></section><section className="pretinha-gallery"><div className="pretinha-section-head"><div><span className="kicker">Galeria final</span><h2>As escolhidas</h2></div><p>{photos.length} de {campaign.selectionLimit} fotos selecionadas</p></div>{photos.length?<div className="pretinha-grid">{photos.map((photo,index)=><article className="pretinha-photo" key={photo.id}><div className="pretinha-photo-image"><Image src={`/api/pretinha/${photo.id}/image`} fill sizes="(max-width:760px) 100vw, (max-width:1100px) 50vw, 33vw" alt={photo.title||`Foto selecionada ${index+1}`}/><span>#{photo.selectedRank??index+1}</span></div>{(photo.title||photo.description)&&<div className="pretinha-photo-copy">{photo.title&&<h3>{photo.title}</h3>}{photo.description&&<p>{photo.description}</p>}</div>}</article>)}</div>:<div className="pretinha-empty"><strong>A galeria está esperando a primeira escolhida.</strong><span>As fotos aparecem aqui depois da seleção.</span></div>}</section>{open?<section className="pretinha-submit" id="enviar"><div className="pretinha-submit-copy"><span className="kicker light">Participe</span><h2>Envie seu registro para esta edição</h2><p>Foto original, com título e descrição opcionais. Esses textos só aparecem publicamente se o registro for selecionado.</p><ul><li>Até 10 MB por envio</li><li>JPG, PNG ou WebP</li><li>Publicação após aprovação dos masters</li></ul></div><PretinhaSubmissionForm campaignId={campaign.id} campaignTitle={campaign.title}/></section>:<section className="campaign-closed"><span className="kicker">Edição encerrada</span><h2>Os envios foram finalizados.</h2><p>A galeria permanece pública como memória da comunidade.</p><Link className="button" href="/olhares">Ver outras edições</Link></section>}</>}
